### ISSUE TITLE
Special Chars are not supported somehow

### ISSUE THREAD

**Issue by kwoxer** [mbostock/topojson#219]
Please have a look on this SO topic: http://stackoverflow.com/questions/28287192/topojson-is-not-correctly-converting-special-chars-from-geojson-like-%C3%AB-or-%C3%B3

Somehow special chars are not correctly converted from my geojson files. How comes?

**Comment by mbostock** [comment]
It’s unlikely to be an issue with the `topojson` command-line tool, which reads UTF-8 input and writes UTF-8 output. (Except in the case of a shapefile’s `.dbf` file, which defaults to ISO-8859-1 for historical reasons and can be customized using the `--shapefile-encoding` argument.)

So, I’m guessing your GeoJSON files aren’t in UTF-8 or are otherwise munged. If you want to create a [Gist](https://gist.github.com) containing your files so that I can take a look, then I will. (I did see you posted something to filedropper, but it looks like a sketchy website and I didn’t want to download something suspicious. I’d prefer being able to look at the contents on Gist before downloading.)

**Comment by kwoxer** [comment]
Hey @mbostock good find, I simply forgot the choose UTF-8 in the QGIS geojson export dialog.

Now it's working properly, thank you very much. And next time as Gist for sure.
