### ISSUE TITLE
Horizontal Lines in World Examples

### ISSUE THREAD

**Issue by j0hj0h** [mbostock/topojson#242]
Both world examples (world-50m.json and world-110m.json) are displayed like this in the GitHub Preview:

![bildschirmfoto 2015-05-27 um 10 42 18](https://cloud.githubusercontent.com/assets/3071485/7832209/8484facc-045d-11e5-97d9-8409c4307dec.png)

The same problem occurs, using the files with OpenLayers 3, and with Leaflet, with the topojson converted to GeoJSON via topojson.js.

Only D3 displays it correctly. But there I had the same problem before – I don't remember under which circumstances, I guess it was with topojson files, I converted myself from Natural Earth shapefiles.

**Comment by rajanski** [comment]
Was already mention in a different visual  expression here https://github.com/mbostock/topojson/issues/164#issuecomment-49104293
Solution proposed here https://github.com/mbostock/topojson/issues/164#issuecomment-49156033
Cheers @j0hj0h ;-)

**Comment by j0hj0h** [comment]
Are the parameters `--q0 0` and `--q0 1e6`meant for the topojson command line converter?
I tried it, but no success ... still the same lines. This is my command:

```
topojson \
  -o world.topo.json \
  --id-property iso_a2 \
  --q0 1e6 \
  -- \
  world.geo.json
```

**Comment by rajanski** [comment]
It is definitely connected with the northeastern part of Russia being a separate polygon (split at 180 degrees east/west line) . If I remove Russia from the topojson it shows fine:
![image](https://cloud.githubusercontent.com/assets/5739684/7836036/930ffeaa-047d-11e5-9b10-3e68c7b9878f.png)

**Comment by j0hj0h** [comment]
Yes, that is what we've tested also. Russia and Fiji, the two features crossing the date line are causing this.

Here is an issue adressing the problem in Leaflet: https://github.com/Leaflet/Leaflet/issues/82
... it's closed, but I don't get the last comment. Is there some manual conversion / wrapping required now?

**Comment by j0hj0h** [comment]
When converting with `--stitch-poles false` the problem disappears. Then Antarctica get's messed up. We don't need Antarctica for the current project, so we deleted it.

**Comment by filipesilva** [comment]
I'm having the same issue, converting natural earth's `.shp` files via `topojson`.

Setting `--q0 0` or `--q0 1e6` did not seem to make a difference, but `--stitch-poles false` fixed it at the expense of Antartica.

**Comment by mbostock** [comment]
The issue is that the software you are using to display this geometry doesn’t truly understand spherical coordinates, or more specifically, spherical topology. These artifacts appears most prominently in Russia because it is a large country and it crosses the [antimeridian](https://en.wikipedia.org/wiki/180th_meridian) (±180° longitude). To display spherical geometry correctly you need rendering software that applies [antimeridian cutting](http://bl.ocks.org/mbostock/3788999), such as D3.

Alternatively, you must “bake-in” an antimeridian cut (typically at ±180° longitude, but it depends on the rotation you desire), so that it can be rendered correctly in software that does not understand spherical topology, such as OpenLayers and Leaflet. Most GeoJSON files include a baked-in antimeridian cut, but this was explicitly rejected for D3 and TopoJSON so that it could properly handle projections with any aspect and rotation.

(This issue is unrelated to mbostock/topojson#164, which is a different type of artifact not related to the antimeridian.)

**Comment by filipesilva** [comment]
Ah, that makes sense. Thank you for the explanation Mike!

**Comment by chrisregner** [comment]
How do I "'bake-in'" an antimeridian cut"? Can you share some resource where I can learn doing it?

**Comment by mbostock** [comment]
@chrisregner Typically you would bake in a planar projection rather than just baking in the antimeridian cut. See [Command-Line Cartography](https://medium.com/@mbostock/command-line-cartography-part-1-897aa8f8ca2c) for an example of [geoproject](https://github.com/d3/d3-geo-projection/blob/master/README.md#geoproject).

That said, you can reproduce (at least if you are willing to treat the Earth as a sphere) the WGS84 coordinate system used in GeoJSON using [d3.geoEquirectangular](https://github.com/d3/d3-geo/blob/master/README.md#geoEquirectangular). Whereas D3 and TopoJSON use spherical coordinates to represent spherical geometry, GeoJSON uses planar equirectangular (plate carrée) coordinates. The difference between WGS84 and d3.geoEquirectangular is that the latter has +*y* pointing down consistent with Canvas and SVG, whereas WGS84 has +*y* (*latitude*) pointing up representing north.

So, to approximate WGS84, you first need to project to d3.geoEquirectangular, and then you need to use [d3.geoIdentity](https://github.com/d3/d3-geo/blob/master/README.md#geoIdentity) to flip the *y*-axis. Here’s an example using the [world-atlas](https://github.com/topojson/world-atlas) as input:

```bash
topo2geo countries=- -i world/110m.json \
  | geoproject 'd3.geoEquirectangular().scale(180 / Math.PI).translate([0, 0])' \
  | geoproject 'd3.geoIdentity().reflectY(true)' \
  > countries.json
```

(The scale factor of 180 / π converts radians to degrees.)

Here’s the result:

<img width="980" alt="screen shot 2017-09-07 at 7 49 14 am" src="https://user-images.githubusercontent.com/230541/30169384-1b962fce-93a1-11e7-8b47-52ecb5491133.png">

**Comment by chrisregner** [comment]
@mbostock Thank you. Actually, I'm trying to incorporate this with a reproduction of your [tutorial](https://bost.ocks.org/mike/leaflet/), which is done in the browser and not in command-line. I'll continue tinkering with existing code until I get the result I need but actually, I have no idea how to do it.

Also, to be honest, I don't understand most of the terms you've mentioned. I'm genuinely trying and I've read some of your articles already. If you have any, can you share some more introductory resources which can make my journey in programming cartography smoother? These are what I've read so far:

- http://maptimeboston.github.io/d3-maptime/
- https://medium.com/@mbostock/command-line-cartography-part-1-897aa8f8ca2c
- https://bost.ocks.org/mike/leaflet/

**Comment by mbostock** [comment]
@chrisregner If you want to use Leaflet or another display library that expects planar input (rather than spherical input as d3-geo expects), then the easiest thing is probably to avoid running [geostitch](https://github.com/d3/d3-geo-projection/blob/master/README.md#geostitch) on your GeoJSON and to keep your data in planar coordinates.

In other words, you probably don’t want to consume the TopoJSON [world-atlas](https://github.com/topojson/world-atlas) as-is, because it is in spherical rather than planar coordinates. You could edit [its prepublish script](https://github.com/topojson/world-atlas/blob/master/prepublish#L18) to remove the call to geostitch.

Yes, you can undo the effect of geostitch on the command-line using the above code, or you can likely achieve the same result directly in the browser using [d3.geoProject](https://github.com/d3/d3-geo-projection/blob/master/README.md#geoProject), but it’s easier if you avoid the conversion to spherical coordinates in the first place. Most shapefiles and GeoJSON you’ll find on the internet are in a planar format.

D3 uses spherical coordinates to allow the geometry to be rotated for arbitrary aspects. This only works because D3 treats the Earth as a sphere, which is generally fine for thematic mapping but not for producing accurate large-scale reference maps.

**Comment by chrisregner** [comment]
I reproduced the TopoJSON just as how you instructed and it did it! I'm very grateful, @mbostock.
