### ISSUE TITLE
Missing topojson.js from 1.6.19 to 1.6.20

### ISSUE THREAD

**Issue by phil-hachey** [mbostock/topojson#267]
topojson.js is no longer being included in versions > 1.6.19. Did the build process change? If so this may have been more appropriate in major version update.

**Comment by mbostock** [comment]
This change occurred in [1.6.21](https://github.com/mbostock/topojson/releases/tag/v1.6.21); the source files are now ES6 modules, and the UMD bundle is built by [Rollup](http://rollupjs.org).

I apologize for the inconvenience, but I do not consider the names of the source files in the git repository to be part of the public API. The public entry point is defined by the “main” entry in the package.json file when using CommonJS (e.g., Node), or the “browser” entry when using Browserify.

In other environments, the location of the UMD bundle is at your discretion. You can build the bundle yourself, or you can access the bundle from [the npm registry](https://www.npmjs.com/package/topojson), [the GitHub release](https://github.com/mbostock/topojson/releases/latest), [the hosted copy on d3js.org](http://d3js.org/topojson.v1.js), or [a CDN of your choice](https://cdnjs.com/libraries/topojson).

1.6.21 also removed support for Bower, since Bower requires that generated files reside in the git repository. This has long been a pain in my side, and I’m no longer willing to do this. Due to the design of Bower, there’s no way to stop publishing versions, other than unregistering it. If you like, I can do that.
