### ISSUE TITLE
GeoJSON to TopoJSON conversions produce ugly bands for countries straddling the 180 degree meridian

### ISSUE THREAD

**Issue by edwingustafson** [mbostock/topojson#278]
Russia straddles the 180 degree meridian. Converting its GeoJSON to TopoJSON yields ugly bands around the globe.

https://github.com/LonnyGomes/CountryGeoJSONCollection/blob/master/geojson/RUS.geojson

https://github.com/LonnyGomes/CountryGeoJSONCollection/blob/master/topojson/RUS.topojson

Fiji yields similar ugly bands in the southern hemisphere for the same reason.

https://github.com/LonnyGomes/CountryGeoJSONCollection/blob/master/geojson/FJI.geojson

https://github.com/LonnyGomes/CountryGeoJSONCollection/blob/master/topojson/FJI.topojson

**Comment by mbostock** [comment]
The software that you are using to render TopoJSON (in this case, GitHub’s use of Leaflet) doesn’t understand spherical coordinates. Specifically, it assumes that spherical coordinates are already cut along the antimeridian with a default aspect, so that the spherical geometry can be projected on a point-by-point basis.

See this demonstration of antimeridian cutting:

[![screen shot 2016-04-19 at 12 05 41 pm](https://cloud.githubusercontent.com/assets/230541/14652019/4341ecd8-0627-11e6-9199-c87084a2a4e7.png)](https://bl.ocks.org/mbostock/3788999)

And compare to what happens if you don’t use antimeridian cutting:

[![screen shot 2016-04-19 at 12 06 49 pm](https://cloud.githubusercontent.com/assets/230541/14652013/3b211b28-0627-11e6-86bc-d8332a32b7e1.png)](http://bl.ocks.org/mbostock/5735770)

D3 supports antimeridian cutting.

You may also be able to avoid antimeridian stitching when converting to TopoJSON using the TopoJSON command-line tool’s `--cartesian` option.
