### ISSUE TITLE
1.6.27 - topojson is undefined

### ISSUE THREAD

**Issue by brendandgibson** [mbostock/topojson#285]
I just updated to 1.6.27

my code:

   import topojson from 'topojson';

topojson is null or undefined.

Rolled back to 1.6.26 === no problem.

**Comment by mbostock** [comment]
There is no default export, so you were benefitting from a bug in an earlier version of Rollup that was upgraded in 1.6.27. You need to import topojson as a namespace:

```js
import * as topojson from "topojson";
```

See https://github.com/mbostock/topojson/blob/master/client.js for what is exported.

**Comment by brendandgibson** [comment]
Thanks @mbostock, that works.

**Comment by nhusher** [comment]
@mbostock I disagree with your rationale for a couple reasons; perhaps you've already considered them in which case, feel free to disregard:

1. You bumped an upstream dependency that changed your public API. It may have been a bug that the API was exposed at all, but it's also a bug that at lest two people were relying upon. I spent a bunch of time last weekend chasing this issue down, and it took me a long time to check the library versions because minor version numbers usually don't have API changes.

2. All the [API reference examples](https://github.com/mbostock/topojson/wiki/API-Reference) use a `topojson` object as the API entrypoint, and there are no ES6 examples. I think it's reasonable for a library user to assume that the ES6 API is very similar to the ES5/browser API, but it is not.

**Comment by mbostock** [comment]
Thanks for the feedback. I know the documentation needs work. Unfortunately I have not had time to work on it. Contributions to documentation and examples are very welcome.

**Comment by jrgleason** [comment]
I just tried this with...

import * as topojson from "topojson";

And I get...

"export 'object' (imported as 'topojson') was not found in 'topojson'
